name: Turnstile
version: "1.0-SNAPSHOT"
author: Your Name
main: dev.turnstile.MyPlugin
api-version: 1.19
commands:
  turnstile:
    description: Desc
    usage: /<command>
    permission: turnstile.use
