name: Turnstile
version: "1.0"
author: Lamune
main: dev.turnstile.TurnstileRenewed
api-version: 1.19
depend: [Vault]
commands:
  turnstile:
    description: Main command.
    usage: /<command>
    permission: turnstile.use
  turnstile help:
  